stages:
  - build

build_devJanet:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  only:
    - devJanet
  script:
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:devJanet --tag $CI_REGISTRY_IMAGE:devJanet .
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:devJanet

build_prod:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  only:
    - tags
    - /^v*$/
  script:
    - echo "Using tag $CI_COMMIT_TAG for image"
    - docker login -u $CI_REGISTRY_USER -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE --all-tags
